name: lingui_quest
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  feather_icons: ^1.2.0
  provider: ^6.0.5
  flutter_portal: ^1.1.4
  flutter_svg: ^2.0.7
  flutter_localization: ^0.1.12
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  equatable: ^2.0.5
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/