// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD3UDEz1CKo3ap82Xk42g0s9Ing44uo1k',
    appId: '1:836741756103:web:e9c8ea29f9567a2619fae2',
    messagingSenderId: '836741756103',
    projectId: 'lingui-quest',
    authDomain: 'lingui-quest.firebaseapp.com',
    storageBucket: 'lingui-quest.appspot.com',
    measurementId: 'G-3YF9SYMHE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcPsaLqM97sw6cb-zjKGfoL0b51hpRr48',
    appId: '1:836741756103:android:df75f348201bbc3f19fae2',
    messagingSenderId: '836741756103',
    projectId: 'lingui-quest',
    storageBucket: 'lingui-quest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWbapy_4gnm6h70G2obAzYBapF7NFWHcg',
    appId: '1:836741756103:ios:7571ac0595c93ac019fae2',
    messagingSenderId: '836741756103',
    projectId: 'lingui-quest',
    storageBucket: 'lingui-quest.appspot.com',
    iosClientId: '836741756103-neaha8mkp7ufrt0p02ktq4cfsk9il7a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.linguiQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWbapy_4gnm6h70G2obAzYBapF7NFWHcg',
    appId: '1:836741756103:ios:854d5bacbaf10b7819fae2',
    messagingSenderId: '836741756103',
    projectId: 'lingui-quest',
    storageBucket: 'lingui-quest.appspot.com',
    iosClientId: '836741756103-ou5gn77mv8p8pjqvdf059culj9rclfiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.linguiQuest.RunnerTests',
  );
}
